sudo: required

language: ruby

rvm:
- 2.2.3

services:
  - docker

env:
  - DOCKER_IMAGE=changeworld/vso-agent-scala

before_script:
  - docker build -t $DOCKER_IMAGE .

script:
  - bundle; bundle exec rspec
